"""Regenera las páginas estáticas. Python 3, sin dependencias."""
from pathlib import Path
from html import escape
root = Path(__file__).parent / 'docs'
root.mkdir(exist_ok=True)
nav = [('soluciones.html','Soluciones'),('productos.html','Productos'),('proyectos.html','Proyectos'),('taller.html','El taller')]
def image(name,alt,hero=False):
 return f'<img src="assets/{name}.webp" alt="{alt}" width="1200" height="900" '+('fetchpriority="high"' if hero else 'loading="lazy"')+' decoding="async">'
def photo(name,alt,hero=False):
 return '<figure>'+image(name,alt,hero)+('<figcaption>Imagen conceptual · Referencia de aplicación</figcaption>' if name in ('hero','display','workshop') else '')+'</figure>'
def button(label,href='contacto.html',secondary=False):
 return f'<a class="button {"secondary" if secondary else ""}" href="{href}">{label}</a>'
def cta():
 return '<section class="contact-band wrap"><div><p class="eyebrow">Empecemos por tu idea</p><h2>Cuéntanos qué necesitas fabricar.</h2><p>Una referencia, unas medidas o una idea son un buen comienzo.</p></div>'+button('Solicitar cotización')+'</section>'
def page(file,title,description,body):
 links=''.join(f'<a href="{url}"'+(' aria-current="page"' if url==file else '')+f'>{label}</a>' for url,label in nav)
 html=f'''<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Santiago Sosa Studio</title><meta name="description" content="{escape(description)}"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#202224"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/styles.css?v=20260912-2"><script src="assets/config.js" defer></script><script src="assets/main.js" defer></script></head><body>
<a class="skip" href="#contenido">Saltar al contenido</a>
<header class="site-header"><div class="wrap header-inner"><a class="brand" href="index.html" aria-label="Santiago Sosa Studio, inicio">Santiago Sosa Studio<span>DISEÑO + FABRICACIÓN</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" hidden>Menú <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Navegación principal">{links}{button('Solicitar cotización')}</nav></div></header>
<main id="contenido">{body}</main>
<footer class="footer"><div class="wrap footer-grid"><a class="brand" href="index.html">Santiago Sosa Studio<span>DISEÑO QUE TOMA FORMA.</span></a><p>Diseño, rotulación y fabricación personalizada.<br>Bávaro–Punta Cana, República Dominicana.</p><a href="contacto.html">Contacto y cotizaciones ↗</a></div><div class="wrap footer-bottom"><span>© <span data-year>2026</span> Santiago Sosa Studio</span><span>Español · República Dominicana</span></div></footer></body></html>'''
 (root/file).write_text(html,encoding='utf-8')
def intro(kicker,title,text):
 return f'<section class="wrap page-intro"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lead">{text}</p></section>'
services=[('rotulacion','Rotulación y publicidad gráfica','Tu marca, presente en el espacio.','Aplicaciones gráficas y elementos de identificación para comunicar tu negocio.','Rótulos · Letras dimensionales · Publicidad gráfica'),('senalizacion','Señalización e identificación','Cada espacio, bien identificado.','Piezas para orientar, numerar e identificar áreas en hoteles, obras y negocios.','Habitaciones · Directorios · Identificación de áreas'),('acrilico','Acrílico y fabricación personalizada','Piezas que se adaptan a tu idea.','Diseño y fabricación de elementos personalizados, con corte y grabado láser CO₂ según el material y el proyecto.','Exhibidores · Placas · Elementos a medida'),('diseno','Diseño gráfico aplicado','El diseño es donde empieza la pieza.','Soluciones gráficas pensadas para su aplicación, sus materiales y su contexto.','Identidad gráfica · Composición · Diseño para producción')]
def servicegrid():
 return '<div class="service-grid">'+''.join(f'<a class="service" href="soluciones.html#{s[0]}"><span class="number">0{i+1}</span><div><h3>{s[1]}</h3><p>{s[3]}</p><span class="text-link">Explorar solución ↗</span></div></a>' for i,s in enumerate(services))+'</div>'
products=[('numero-habitacion','Números de habitación','Identificación para espacios de alojamiento.','hero','Señal de habitación 204 en acrílico oscuro','Señalización','Número, tipografía, formato y acabado según evaluación.'),('exhibidor-acrilico','Exhibidores en acrílico','Presenta información en recepción, mesas o mostradores.','display','Exhibidor conceptual de acrílico transparente','Acrílico','Formato, medidas y aplicación gráfica según evaluación.'),('placa-personalizada','Placas personalizadas','Una pieza para identificar y comunicar.','pictograma','Pictograma de baño en acrílico con película protectora','Fabricación a medida','Texto, diseño, medidas y sistema de colocación según evaluación.')]
def productgrid():
 return '<div class="product-grid">'+''.join(f'<a class="product" href="producto-{p[0]}.html">{image(p[3],p[4])}<span class="eyebrow">{p[5]}</span><h3>{p[1]}</h3><p>{p[2]}</p><span class="text-link">Ver detalles ↗</span></a>' for p in products)+'</div>'
projects=[
 ('bayahibe','Letras monumentales · Bayahibe','Letras de gran formato en su entorno y detalles de acabado.',['bayahibe','bayahibe-detalle']),
 ('quiosco','Rotulación de quiosco turístico','Gráfica aplicada al punto de atención. La estructura de madera fue realizada por otro taller.',['quiosco','quiosco-proceso']),
 ('punta-cana','Letras de gran formato · Punta Cana','Volumen y color para identificar espacios.',['punta-cana']),
 ('oceanpark','Rotulación de embarcación','Identidad gráfica aplicada sobre el casco.',['oceanpark']),
 ('numeracion','Numeración y orientación','Piezas durante su fabricación, todavía con película protectora.',['numeracion','direccion']),
 ('bandera','Banderas en preparación','Piezas gráficas durante su preparación, antes de la colocación.',['bandera-preparacion']),
 ('letras-proceso','Letras: preparación y acabado','Masilla, lijado y pintura: distintas etapas del trabajo en letras de gran formato.',['letras-proceso','letras-pintura'])]
def examples(all_projects=False):
 return '<div class="examples">'+''.join('<a href="proyecto-'+slug+'.html">'+photo(imgs[0],title)+'<h3>'+title+'</h3></a>' for slug,title,desc,imgs in (projects if all_projects else projects[:2]))+'</div>'
body='<section class="wrap hero"><div class="hero-copy"><p class="eyebrow">Bávaro–Punta Cana · República Dominicana</p><h1>Diseño que<br>toma forma.</h1><p class="lead">Diseño gráfico, rotulación y fabricación personalizada para tu negocio.</p><div class="actions">'+button('Solicitar cotización')+button('Ver proyectos','proyectos.html',True)+'</div><p class="hero-note">Ideas, materiales y producción.</p></div>'+photo('hero','Referencia conceptual de señal de habitación 204 con letras en relieve',True)+'</section>'
body+='<section class="wrap section"><div class="section-heading"><div><p class="eyebrow">Trabajos realizados</p><h2>Piezas que hablan<br>por tu negocio.</h2></div><a class="text-link" href="proyectos.html">Ver proyectos ↗</a></div>'+examples()+'</section>'
body+='<section class="section solutions-section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">01 / Capacidades</p><h2>Soluciones a medida.</h2></div><p>Del diseño gráfico a los elementos físicos que tu espacio necesita.</p></div>'+servicegrid()+'</div></section>'
body+='<section class="wrap section"><div class="section-heading"><div><p class="eyebrow">02 / Productos</p><h2>¿Qué necesitas fabricar?</h2></div><a class="text-link" href="productos.html">Ver productos ↗</a></div>'+productgrid()+'</section>'
body+='<section class="wrap section sectors"><p class="eyebrow">03 / Para tu negocio</p><h2>Diseñado para tu espacio.</h2><div class="sector-grid"><a href="soluciones.html#senalizacion"><h3>Hoteles</h3><p>Identificación de habitaciones, orientación y piezas para recepción.</p></a><a href="soluciones.html#rotulacion"><h3>Construcción</h3><p>Identificación y comunicación gráfica para proyectos y espacios.</p></a><a href="soluciones.html#acrilico"><h3>Restaurantes y comercios</h3><p>Marca visible, información clara y elementos personalizados.</p></a></div></section>'
body+='<section class="workshop-band"><div class="wrap workshop-grid">'+photo('letras-proceso','Letras de gran formato con masilla durante la preparación y el lijado')+'<div><p class="eyebrow">04 / El taller</p><h2>Del diseño a la<br>pieza terminada.</h2><p>Diseño y fabricación de soluciones físicas, con materiales y procesos adecuados a cada proyecto.</p><p>Instalación disponible, evaluada y cotizada según el trabajo y la ubicación.</p>'+button('Conocer el taller','taller.html',True)+'</div></div></section>'+cta()
page('index.html','Diseño, rotulación y fabricación en Bávaro–Punta Cana','Diseño gráfico, señalización, acrílico y fabricación personalizada para hoteles, empresas y comercios en Bávaro–Punta Cana.',body)
body=intro('Soluciones','De tu necesidad<br>a una solución física.','Diseño y fabricación para identificar, orientar y comunicar.')+'<div class="wrap anchor-nav">'+''.join(f'<a href="#{s[0]}">{s[1]}</a>' for s in services)+'</div>'
for i,s in enumerate(services):
 body+=f'<section id="{s[0]}" class="wrap section service-detail"><div><span class="number">0{i+1}</span><h2>{s[1]}</h2></div><div><h3>{s[2]}</h3><p class="lead">{s[3]}</p><p>{s[4]}</p><p>El material, las medidas, el acabado y la colocación se definen según tu necesidad.</p>'+button('Consultar esta solución',f'contacto.html?interes={s[0]}')+'</div></section>'
page('soluciones.html','Soluciones','Rotulación, señalización, acrílico y diseño gráfico aplicado.',body+cta())
page('productos.html','Productos personalizados','Explora piezas de señalización, exhibidores y fabricación personalizada.',intro('Productos','Piezas para tu negocio.<br>Hechas a tu medida.','Explora piezas que podemos adaptar a tu espacio. Las imágenes conceptuales están identificadas; las fotografías de producción muestran piezas en proceso. Los materiales, medidas y acabados se confirman al cotizar.')+'<section class="wrap catalog">'+productgrid()+'</section>'+cta())
for p in products:
 body=intro(p[5],p[1],p[2])+f'<section class="wrap detail-grid">{photo(p[3],p[4],True)}<div><p class="eyebrow">Personalización a medida</p><h2>Adaptado a tu proyecto.</h2><dl><dt>Personalización</dt><dd>{p[6]}</dd><dt>Medidas y materiales</dt><dd>Se definen según el uso, el diseño y la cantidad.</dd><dt>Instalación</dt><dd>Cuando corresponda, se evalúa y cotiza según la complejidad y el desplazamiento.</dd></dl>'+button('Cotizar este producto',f'contacto.html?interes={p[0]}')+'<p class="small">Puedes comenzar con una referencia o una idea. No necesitas tener el diseño terminado.</p></div></section>'
 page(f'producto-{p[0]}.html',p[1],p[2],body+cta())
page('proyectos.html','Proyectos realizados','Rotulación, letras de gran formato y señalización.',intro('Proyectos','El diseño en su contexto.','Una selección de rotulación, letras de gran formato y piezas en fabricación.')+'<section class="wrap catalog">'+examples(True)+'</section>'+cta())
for slug,title,desc,imgs in projects:
 gallery='<section class="wrap project-gallery">'+''.join(photo(img,title if i==0 else 'Detalle del trabajo: '+title,i==0) for i,img in enumerate(imgs))+'</section>'
 page('proyecto-'+slug+'.html',title,desc,intro('Trabajos realizados',title,desc)+gallery+cta())

for slug,title,img,desc in [('senalizacion','Identificación de habitaciones','hero','Una referencia de señalización que combina contraste, numeración visible y relieve.'),('exhibidor','Información en el punto de atención','display','Una referencia de exhibidor transparente para presentar información en mesas y mostradores.')]:
 page(f'proyecto-{slug}.html',title,desc,intro('Aplicación ilustrativa · No es un proyecto ejecutado',title,desc)+f'<section class="wrap detail-grid">{photo(img,title,True)}<div><h2>Una idea para tu espacio.</h2><p>El diseño final, el material y el sistema de colocación dependen de las condiciones de uso y de tu identidad gráfica.</p><p>Esta imagen sirve como referencia conceptual. Puedes ver trabajos realizados en nuestra sección de proyectos.</p>'+button('Consultar un trabajo similar',f'contacto.html?interes={slug}')+'</div></section>'+cta())
body=intro('El taller','Diseño, materiales<br>y fabricación.','Santiago Sosa Studio reúne diseño gráfico y producción de elementos personalizados en Bávaro–Punta Cana.')+'<section class="wrap detail-grid">'+photo('laser','Corte de placas de numeración en máquina láser',True)+'<div><h2>De la idea al objeto.</h2><p>Trabajamos en rotulación, señalización, productos en acrílico y soluciones gráficas para empresas y particulares.</p><p>El corte y grabado láser CO₂ forma parte de nuestras capacidades de fabricación. Evaluamos cada pieza según su diseño, material y aplicación.</p></div></section><section class="wrap section"><p class="eyebrow">Cómo trabajamos</p><h2>Cada paso tiene su propósito.</h2><ol class="process"><li><h3>Consulta</h3><p>Entendemos la pieza, su uso, cantidad y fecha deseada.</p></li><li><h3>Propuesta</h3><p>Definimos diseño, alcance y presupuesto.</p></li><li><h3>Aprobación</h3><p>Acordamos los detalles antes de fabricar.</p></li><li><h3>Fabricación</h3><p>Producimos la solución acordada.</p></li><li><h3>Entrega o instalación</h3><p>Según lo cotizado. La instalación considera complejidad, ubicación y desplazamiento.</p></li></ol></section>'
body+='<section class="wrap section"><p class="eyebrow">El proceso en detalle</p><h2>Preparar, lijar y dar color.</h2><p>Cada acabado lleva trabajo. Estas fotografías muestran piezas en distintas etapas de fabricación.</p><div class="project-gallery process-gallery">'+photo('letras-proceso','Letras con masilla y herramienta de lijado')+photo('letras-pintura','Letras de colores con acabado de pintura en el taller')+'</div></section>'
page('taller.html','El taller','Estudio de diseño y taller de fabricación personalizada en Bávaro–Punta Cana.',body+cta())
body=intro('Contacto','Cuéntanos qué<br>necesitas fabricar.','Puedes comenzar con una idea, una fotografía o una referencia. Te ayudaremos a definir el alcance.')+'<section class="wrap contact-layout"><div><p id="interest" class="interest" hidden></p><h2>Hablemos de tu proyecto.</h2><div class="contact-options"><a id="whatsapp" class="button" hidden>Contactar por WhatsApp</a><a id="email" class="button secondary" hidden>Enviar correo</a></div><p id="contact-pending" class="notice">Los canales de contacto estarán disponibles próximamente.</p><noscript><p>Activa JavaScript para mostrar los canales de contacto.</p></noscript><p>Bávaro–Punta Cana<br>República Dominicana</p></div><aside><p class="eyebrow">Para preparar tu cotización</p><h3>Si lo tienes, compártenos:</h3><ul class="quote-list"><li>Qué pieza o solución necesitas.</li><li>Cantidad y medidas aproximadas.</li><li>Una referencia visual.</li><li>La fecha deseada.</li></ul><p>No necesitas tener todos los detalles para comenzar.</p><div class="installation"><h3>¿Necesitas instalación?</h3><p>Incluye la ubicación y fotografías del lugar. La instalación se evalúa y cotiza según las condiciones de cada trabajo.</p></div></aside></section>'
page('contacto.html','Solicitar cotización','Consulta tu proyecto de diseño, señalización o fabricación personalizada.',body)
print(f'Generadas {len(list(root.glob("*.html")))} páginas')
